// packages/history-restoration/src/pages/react/AsyncLinkList.jsx
import React, { Suspense } from 'react';
import { service } from '../../service';
import { useHistoryRestoration } from '../../useHistoryRestoration';
import LinkList from './LinkList.jsx';
import Loading from './Loading.jsx';

const AsyncLinkListHOC = React.lazy(async () => {
  const links = await service.getLinks();
  function LazyLinkList() {
    const historyRestoration = useHistoryRestoration();
    React.useEffect(() => {
      // scroll to saved scroll position after link list rendered
      historyRestoration.done();
    }, []);
    return React.createElement(LinkList, { links });
  }
  return { default: LazyLinkList };
});

export default function AsyncLinkList() {
  return (
    <Suspense fallback={<Loading />}>
      <AsyncLinkListHOC />
    </Suspense>
  );
}

// packages/history-restoration/src/pages/vue/AsyncLinkList.vue
<script setup>
import { defineAsyncComponent, h, onMounted } from 'vue';
import { createHistoryRestoration } from '../../historyRestoration';
import { service } from '../../service';
import LinkList from './LinkList.vue';

const historyRestoration = createHistoryRestoration();

const AsyncLinkList = defineAsyncComponent(async () => {
  const links = await service.getLinks();
  return {
    setup() {
      onMounted(() => {
        // scroll to saved scroll position after link list rendered
        historyRestoration.onLoad();
      });
      return () => h(LinkList, { links });
    },
  };
});
</script>

<template>
  <AsyncLinkList />
</template>
