// packages/scroll-restoration/src/react/ScrollRestorationDone.tsx
import { useEffect } from 'react';
import { useScrollRestoration } from './useScrollRestoration';

export default function ScrollRestorationDone() {
  const scrollRestoration = useScrollRestoration();
  useEffect(() => {
    // scroll to saved scroll position after link list rendered
    scrollRestoration.done();
  }, []);
  return null;
}

// packages/scroll-restoration/src/vue/ScrollRestorationDone.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { useScrollRestoration } from './useScrollRestoration';

const scrollRestoration = useScrollRestoration();

onMounted(() => {
  // scroll to saved scroll position after link list rendered
  scrollRestoration!.onLoad();
});
</script>

<template></template>
