// packages/history-restoration/src/pages/react/App.jsx
import React, { StrictMode } from 'react';
import AsyncLinkList from './AsyncLinkList.jsx';
import LargeBlock from './LargeBlock.jsx';
import PoweredByReact from './PoweredByReact.jsx';

export default function App() {
  return (
    <StrictMode>
      <LargeBlock />
      <LargeBlock />
      <LargeBlock />
      <AsyncLinkList />
      <PoweredByReact />
      <LargeBlock />
      <LargeBlock />
    </StrictMode>
  );
}

// packages/history-restoration/src/vue/App.vue
<script setup>
import PoweredByVue from './PoweredByVue.vue';
import LargeBlock from './LargeBlock.vue';
import AsyncLinkList from './AsyncLinkList.vue';
</script>

<template>
  <div>
    <LargeBlock />
    <LargeBlock />
    <LargeBlock />
    <AsyncLinkList />
    <PoweredByVue />
    <LargeBlock />
    <LargeBlock />
  </div>
</template>
