// packages/scroll-restoration/src/vue/App.vue
<script setup lang="ts">
import AsyncLinkList from './AsyncLinkList.vue';
import LargeBlock from './LargeBlock.vue';
import PoweredByVue from './PoweredByVue.vue';
</script>

<template>
  <main>
    <h2>Vue page</h2>
    <AsyncLinkList />
    <LargeBlock />
    <LargeBlock />
    <LargeBlock />
    <AsyncLinkList />
    <LargeBlock />
    <LargeBlock />
    <AsyncLinkList />
  </main>
  <footer>
    <PoweredByVue />
  </footer>
</template>

// packages/scroll-restoration/src/react/App.tsx
import React, { StrictMode } from 'react';
import AsyncLinkList from './AsyncLinkList';
import LargeBlock from './LargeBlock';
import PoweredByReact from './PoweredByReact';

export default function App() {
  return (
    <StrictMode>
      <main>
        <h2>React page</h2>
        <AsyncLinkList />
        <LargeBlock />
        <LargeBlock />
        <LargeBlock />
        <AsyncLinkList />
        <LargeBlock />
        <LargeBlock />
        <AsyncLinkList />
      </main>
      <footer>
        <PoweredByReact />
      </footer>
    </StrictMode>
  );
}
