// packages/scroll-restoration/src/vue/AsyncLinkList.vue
<script setup lang="ts">
import { h } from 'vue';
import { service } from '../lib/service';
import LinkList from './LinkList.vue';
import { useAsyncComponent } from './useAsyncComponent';

const AsyncLinkListHOC = useAsyncComponent(async () => {
  const links = await service.getLinks();
  return h(LinkList, { links });
});
</script>

<template>
  <AsyncLinkListHOC />
</template>

// packages/scroll-restoration/src/react/AsyncLinkList.tsx
import React, { Suspense } from 'react';
import { service } from '../lib/service';
import LinkList from './LinkList';
import Loading from './Loading';
import { useAsyncComponent } from './useAsyncComponent';

export default function AsyncLinkList() {
  const AsyncLinkListHOC = useAsyncComponent(async () => {
    const links = await service.getLinks();
    return <LinkList links={links} />;
  });
  return (
    <Suspense fallback={<Loading />}>
      <AsyncLinkListHOC />
    </Suspense>
  );
}
