// packages/scroll-restoration/src/vue/AsyncLinkList.vue
<script setup lang="ts">
import { Component, defineAsyncComponent, h, onMounted } from 'vue';
import { createHistoryRestoration } from '../lib/historyRestoration';
import { service } from '../lib/service';
import LinkList from './LinkList.vue';

const historyRestoration = createHistoryRestoration();

const AsyncLinkListHOC = defineAsyncComponent(async () => {
  const links = await service.getLinks();
  const AsyncLinkList: Component = {
    setup() {
      onMounted(() => {
        // scroll to saved scroll position after link list rendered
        historyRestoration.onLoad();
      });
      return () => h(LinkList, { links });
    },
  };
  return AsyncLinkList;
});
</script>

<template>
  <AsyncLinkListHOC />
</template>

// packages/history-restoration/src/react/AsyncLinkList.tsx
import React, { Suspense } from 'react';
import { service } from '../lib/service';
import { useHistoryRestoration } from '../lib/useHistoryRestoration';
import LinkList from './LinkList';
import Loading from './Loading';

const AsyncLinkListHOC = React.lazy(async () => {
  const links = await service.getLinks();
  function LazyLinkList() {
    const historyRestoration = useHistoryRestoration();
    React.useEffect(() => {
      // scroll to saved scroll position after link list rendered
      historyRestoration.done();
    }, []);
    return React.createElement(LinkList, { links });
  }
  return { default: LazyLinkList };
});

export default function AsyncLinkList() {
  return (
    <Suspense fallback={<Loading />}>
      <AsyncLinkListHOC />
    </Suspense>
  );
}
